name: Deploy Marketing Assets test Version

on:
  push:
    branches: [develop]

jobs:
  build:
    name: Marketing Assets CI

    strategy:
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 18.x
        architecture:
          - x64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          check-latest: false
          architecture: ${{ matrix.architecture }}

      - name: Install dependencies
        run: yarn

      - name: Setup env file
        run: |
          touch .env.production
          echo DB_NAME=marketingasset >> .env.production
          echo DB_HOST=dedi2849.your-server.de >> .env.production
          echo DB_PORT=3306 >> .env.production
          echo DB_USERNAME=marketingasset >> .env.production
          echo DB_PASSWORD=HrDK94hB6Qzy1jnM >> .env.production
          echo NEXT_PUBLIC_FRONT_BASE_URL=https://test.cufinder.io >> .env.production
          echo NEXT_PUBLIC_API_BASE_URL=https://test.cufinder.io/api >> .env.production
          echo NEXT_PUBLIC_EXTERNAL_BASE_URL=https://cufinder.io >> .env.production
          echo NEXT_PUBLIC_EXTERNAL_DASHBOARD_BASE_URL=https://dashboard.cufinder.io >> .env.production
          echo NEXT_PUBLIC_IMAGE_BASE_URL=https://cufinder.io/marketing/assets/img >> .env.production

      - name: Build app
        run: yarn build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftps
          security: loose
          timeout: 600000
          server-dir: public_html/test/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.husky/**
            **/src/**
            **/data/**
            **/styles/**
            **/.editorconfig
            **/.env
            **/.eslintcache
            **/.eslintrc.json
            **/.prettierrc.js
            **/CHANGELOG.md
            **/commitlint.config.js
            **/jsconfig.json
            **/tsconfig.json
            **/yarn.lock
